### ISSUE TITLE
Continuing with dukesrg branch

### ISSUE THREAD

**Issue by mariogamer2** [astronautlevel2/astronautlevel2.github.io#8]
@dukesrg is reverse engineering rxTools [here](https://github.com/dukesrg/rxTools),and this will be good to provide these build.

**Comment by astronautlevel2** [comment]
I have no plans to support builds for a WIP that doesn't even build half the time. 

Besides, rxTools is dated. Its tools are done better by decrypt9 and its CFW is done better by ReiNAND/Luma/Cakes.

**Comment by mariogamer2** [comment]
Not totally,dukesrg is improving and work on a lot of things: https://github.com/dukesrg/rxTools/issues

**Comment by astronautlevel2** [comment]
I'm aware of duke_srg's work, however I still can't justify bringing back a nightly site for two reasons:
1. All the tools that rxTools has are done better by decrypt9. Period, this is not debatable. Without the advantage of its tools, it becomes {insert generic CFW here}
2. Most of the commits are in the middle of refactoring and won't even build properly.
