### ISSUE TITLE
Incorrect Builds/Versions for Luma3DS builds

### ISSUE THREAD

**Issue by cheatfreak47** [astronautlevel2/astronautlevel2.github.io#9]
As requested, I moved [StarUpdater Issue #15](https://github.com/astronautlevel2/StarUpdater/issues/15) to your website's github, instead becase it's apparently a server side bug. ^_^

In your own words: 
"Probably something borked with lastVer checking. Either that or Aurora committed something weirdly and caused my (rather hacky) lastVer checking to fail.
I'll fix it manually for now and close this, I'd prefer this issue to be re-opened on my site's github."

**Comment by cheatfreak47** [comment]
Oops wrong github. My bad.

**Comment by astronautlevel2** [comment]
Third time's the charm :stuck_out_tongue:
